### ISSUE TITLE
Running as a Docker Container

### ISSUE THREAD

**Issue by cgmartin** [langchain-ai/ollama-deep-researcher#27]
Can anyone share a `Dockerfile` or `docker-compose.yaml` for running `ollama-deep-researcher` as a containerized service?

At very quick glance it seems like this would be fairly straightforward to do using a base python image.

I may try to take a stab at this if no one has one written yet, but wanted to ask first.

**Comment by silverfisk** [comment]
I built the image like so:

```Dockerfile
FROM python:3.11 as build

ADD https://astral.sh/uv/install.sh /var/tmp/uv-install.sh

RUN useradd -m agent -d /app
RUN  chmod 0755 /var/tmp/uv-install.sh && chown agent /var/tmp/uv-install.sh

USER agent

RUN /var/tmp/uv-install.sh

RUN rm -f /var/tmp/uv-install.sh

WORKDIR /app

COPY --chown=agent . /app/

ENV PATH=/app/.local/bin:$PATH

RUN uvx --refresh --from "langgraph-cli[inmem]" --with-editable . --python 3.11 langgraph --version

ENTRYPOINT uvx --refresh --from "langgraph-cli[inmem]" --with-editable . --python 3.11 langgraph dev
```

And have a docker-compose containing this this:
```yaml
  ollama-deep-researcher:
    build: ./ollama-deep-researcher
    container_name: ollama-deep-researcher
    env_file:
      - .env_ollama-deep-researcher
    depends_on:
      - ollama
    ports:
      - "2024:2024"
```

However, there seem to be some hard-coding to only listen to 127.0.0.1, so it cannot be accessed right now
